name: macOS CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

concurrency:
  group: macos-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test (macOS)
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Cache SwiftPM build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            .build
          key: ${{ runner.os }}-swiftpm-${{ hashFiles('Package.swift', 'Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swiftpm-

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build package (release)
        run: swift build --configuration release --build-tests -Xswiftc -enable-testing

      - name: Run unit tests (release)
        run: swift test --configuration release -Xswiftc -enable-testing

      - name: Run benchmark test product (release)
        run: swift test --configuration release --test-product SpecificationKitBenchmarks -Xswiftc -enable-testing

      - name: Build DemoApp (release)
        run: |
          cd DemoApp
          swift build --configuration release
